# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2019
          - windows-2022
        mode:
          - Debug
          - ReleaseFast
          - ReleaseSafe
          - ReleaseSmall
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0
      - name: Check source code
        run: |
          zig build check --summary all
      - name: Build binary artifacts
        run: |
          zig build --summary all -Doptimize=${{ matrix.mode }}
      - name: Build and run tests
        run: |
          zig build test --summary all -Doptimize=${{ matrix.mode }}
